//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostLedger
    {
        public long RecId { get; set; }
        public string LocNo { get; set; }
        public string ItemCode { get; set; }
        public System.DateTime TrDate { get; set; }
        public double RecQty { get; set; }
        public double RecRate { get; set; }
        public double RecTotal { get; set; }
        public double IssQty { get; set; }
        public double IssRate { get; set; }
        public double IssTotal { get; set; }
        public double BalQty { get; set; }
        public double BalRate { get; set; }
        public double BalTotal { get; set; }
        public string UpdSrc { get; set; }
        public string UpdSrcNo { get; set; }
    }
}
