//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public int Id { get; set; }
        public string IssueNo { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public double ExQty { get; set; }
        public string LotNo { get; set; }
        public string SubCode { get; set; }
        public string ItemType { get; set; }
    
        public virtual IssueMain IssueMain { get; set; }
        public virtual ItemInfo ItemInfo { get; set; }
    }
}
