//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueMain
    {
        public IssueMain()
        {
            this.IssueDetails = new HashSet<IssueDetail>();
        }
    
        public string IssueNo { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string FromLocCode { get; set; }
        public string ToLocCode { get; set; }
        public string DesLocCode { get; set; }
        public string Accode { get; set; }
        public string IssueToSubCode { get; set; }
        public string JobNo { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Remarks { get; set; }
        public string IssueByCode { get; set; }
        public string AppByCode { get; set; }
        public System.DateTime IssTime { get; set; }
        public System.DateTime IssDate { get; set; }
        public double Amount { get; set; }
        public string FinYear { get; set; }
        public bool GLPost { get; set; }
        public bool IsReceived { get; set; }
        public string BranchCode { get; set; }
        public bool cashReceiptStatus { get; set; }
        public string StoreLocCode { get; set; }
        public string VchrNo { get; set; }
        public string EntrySrc { get; set; }
        public string EntrySrcNo { get; set; }
    
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
    }
}
