//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMap
    {
        public int Id { get; set; }
        public int ItemTypeCode { get; set; }
        public int GroupID { get; set; }
        public int SGroupID { get; set; }
        public int SSGroupID { get; set; }
        public string ItemCode { get; set; }
    }
}
