//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ASPLEntities : DbContext
    {
        public ASPLEntities()
            : base("name=ASPLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostLedger> CostLedgers { get; set; }
        public virtual DbSet<CurrentStock> CurrentStocks { get; set; }
        public virtual DbSet<CustWiseSummSaleRpt> CustWiseSummSaleRpts { get; set; }
        public virtual DbSet<IssueDetail> IssueDetails { get; set; }
        public virtual DbSet<IssueMain> IssueMains { get; set; }
        public virtual DbSet<ItemInfo> ItemInfoes { get; set; }
        public virtual DbSet<ItemMap> ItemMaps { get; set; }
        public virtual DbSet<SalesDetail> SalesDetails { get; set; }
        public virtual DbSet<SecUserInfo> SecUserInfoes { get; set; }
        public virtual DbSet<tmpAddedItem> tmpAddedItems { get; set; }
        public virtual DbSet<SalesMain> SalesMains { get; set; }
        public virtual DbSet<SysSet> SysSets { get; set; }
    
        public virtual ObjectResult<rptCustomerWiseSummarySales_Result> rptCustomerWiseSummarySales(string finYear, string locCode, Nullable<System.DateTime> fdate, Nullable<System.DateTime> tdate)
        {
            var finYearParameter = finYear != null ?
                new ObjectParameter("finYear", finYear) :
                new ObjectParameter("finYear", typeof(string));
    
            var locCodeParameter = locCode != null ?
                new ObjectParameter("locCode", locCode) :
                new ObjectParameter("locCode", typeof(string));
    
            var fdateParameter = fdate.HasValue ?
                new ObjectParameter("fdate", fdate) :
                new ObjectParameter("fdate", typeof(System.DateTime));
    
            var tdateParameter = tdate.HasValue ?
                new ObjectParameter("tdate", tdate) :
                new ObjectParameter("tdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptCustomerWiseSummarySales_Result>("rptCustomerWiseSummarySales", finYearParameter, locCodeParameter, fdateParameter, tdateParameter);
        }
    
        public virtual ObjectResult<CustWiseSummSale_Result> CustWiseSummSale(string finYear, string locCode, Nullable<System.DateTime> fdate, Nullable<System.DateTime> tdate)
        {
            var finYearParameter = finYear != null ?
                new ObjectParameter("finYear", finYear) :
                new ObjectParameter("finYear", typeof(string));
    
            var locCodeParameter = locCode != null ?
                new ObjectParameter("locCode", locCode) :
                new ObjectParameter("locCode", typeof(string));
    
            var fdateParameter = fdate.HasValue ?
                new ObjectParameter("fdate", fdate) :
                new ObjectParameter("fdate", typeof(System.DateTime));
    
            var tdateParameter = tdate.HasValue ?
                new ObjectParameter("tdate", tdate) :
                new ObjectParameter("tdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CustWiseSummSale_Result>("CustWiseSummSale", finYearParameter, locCodeParameter, fdateParameter, tdateParameter);
        }
    }
}
