//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcclineERPApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysSet
    {
        public int SysId { get; set; }
        public bool Budget { get; set; }
        public bool ConsolidatedCash { get; set; }
        public bool NotProfit { get; set; }
        public bool VouSlTypeWise { get; set; }
        public bool HasProject { get; set; }
        public bool HasBranch { get; set; }
        public bool HasDept { get; set; }
        public bool HasUnit { get; set; }
        public bool HasParty { get; set; }
        public bool MultiFinYear { get; set; }
        public bool HeadWiseNarration { get; set; }
        public bool AlwaysMultiple { get; set; }
        public bool MaintOldCode { get; set; }
        public string BudgetAllocation { get; set; }
        public bool RecurringVoucher { get; set; }
        public bool ShowJobName { get; set; }
        public bool autovouaftersave { get; set; }
        public int VchrLen { get; set; }
        public string MRConv { get; set; }
        public int InvoiceFormat { get; set; }
        public Nullable<bool> MaintJob { get; set; }
        public bool MaintLot { get; set; }
        public bool MaintVAT { get; set; }
        public bool Stockedcheck { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public bool MakeChallanAuto { get; set; }
        public bool MakeRecvAuto { get; set; }
        public bool OnlyGL { get; set; }
        public bool HasRemittance { get; set; }
        public bool IsSubsidiaryCtrl { get; set; }
        public bool NoGrp { get; set; }
        public bool OnlyGrp { get; set; }
        public bool GrpAndSubGrp { get; set; }
        public bool SubSubGrp { get; set; }
        public bool HasSale { get; set; }
        public bool OnlyVAT { get; set; }
        public Nullable<bool> RateChart { get; set; }
        public Nullable<bool> CashBasis { get; set; }
        public Nullable<bool> ActualBasis { get; set; }
        public Nullable<bool> MaintPacking { get; set; }
    }
}
